image: node:latest
tags:
  - docker
stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

  only:
    - v2