image: node:latest
stages:
  - build
  - v2_build
  - test
  - production

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - master
  
v2_build:
  stage: v2_build
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/
  only:
    - v2

is_this_working:
  stage: test
    - npx mocha
  artifacts:
    paths:
      - node_modules/
  only:
    - master

production:
  type: deploy
  stage: production
  image: ubuntu:latest
  environment:
    name: deployment
    url: vibeybot.xyz
  script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh vibey_bot@209.141.36.245 "cd /var/www/vibey_bot/code/vibey_bot && git checkout master && git pull origin master && pm2 restart 0 && exit"
  only:
    - master
